### ISSUE TITLE
Broken Links: Unified Access Control Conditions

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/docs#243]
In https://developer.litprotocol.com/v3/sdk/access-control/condition-types/unified-access-control-conditions/

> For [EVM Basic Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/evm/basic-examples), also known as classic "Access Control Conditions", use the string evmBasic
> For [EVM Custom Contract Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/evm/custom-contract-calls), use the string evmContract
> For [Solana RPC Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/other-chains/sol-rpc-conditions), use the string solRpc
> For [Cosmos or Kyve Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/other-chains/cosmos-conditions), use the string cosmos

Every one of these links is broken

**Comment by Aaryan-R-S** [comment]
Thanks @zach-is-my-name for reporting!
Fixing it.

**Comment by Aaryan-R-S** [comment]
Hey @zach-is-my-name! Links are working fine. 
You have specified a different link (having a '/' at the end of link). This is why `docusauras` hrefs are not working on that. 
This is the right link - 
 https://developer.litprotocol.com/v3/sdk/access-control/condition-types/unified-access-control-conditions

**Comment by Aaryan-R-S** [comment]
Actually this is the issue with Netlify. By default, Netlify adds trailing slashes to Docusaurus URLs.

It is recommended to disable the Netlify setting Post Processing > Asset Optimization > Pretty Urls to prevent lowercase URLs, unnecessary redirects, and 404 errors.

Since we do not want to keep the Pretty Urls Netlify setting on, I will adjust the trailingSlash Docusaurus config appropriately.

Refer to [slorber/trailing-slash-guide](https://github.com/slorber/trailing-slash-guide) and [Deploying to Netlify](https://docusaurus.io/docs/deployment#deploying-to-netlify) for more information.

**Comment by Aaryan-R-S** [comment]
Fixed here #244
